name: LaunchQL tests
on:
  push:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: pyramation/node-sqitch:20.12.0

    env:
      PGHOST: pg_db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password

    services:
      pg_db:
        image: pyramation/pgvector:13.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      minio_cdn:
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
          - 9001:9001
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Configure Git (for tests)
        run: |
          git config --global user.name "CI Test User"
          git config --global user.email "ci@example.com"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v
          node -v

      - name: Install
        run: pnpm install

      - name: Install LaunchQL CLI globally
        run: pnpm add -g @launchql/cli@4.7.2

      - name: Build
        run: pnpm -r build

      - name: Seed app_user
        run: |
          lql admin-users bootstrap --yes
          lql admin-users add --test --yes
        env:
          PGHOST: pg_db
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password

      # Test all LaunchQL modules
      - name: Test data-types/base32
        run: cd ./packages/data-types/base32 && pnpm test

      - name: Test data-types/ext-types
        run: cd ./packages/data-types/ext-types && pnpm test

      - name: Test data-types/ext-uuid
        run: cd ./packages/data-types/ext-uuid && pnpm test

      - name: Test data-types/inflection
        run: cd ./packages/data-types/inflection && pnpm test

      - name: Test data-types/stamps
        run: cd ./packages/data-types/stamps && pnpm test

      - name: Test geo/geotypes
        run: cd ./packages/geo/geotypes && pnpm test

      - name: Test jobs/database-jobs
        run: cd ./packages/jobs/database-jobs && pnpm test

      - name: Test jobs/jobs
        run: cd ./packages/jobs/jobs && pnpm test

      - name: Test meta/db_meta
        run: cd ./packages/meta/db_meta && pnpm test

      - name: Test meta/db_meta_modules
        run: cd ./packages/meta/db_meta_modules && pnpm test

      - name: Test meta/db_meta_test
        run: cd ./packages/meta/db_meta_test && pnpm test

      - name: Test metrics/achievements
        run: cd ./packages/metrics/achievements && pnpm test

      - name: Test metrics/measurements
        run: cd ./packages/metrics/measurements && pnpm test

      - name: Test security/encrypted-secrets
        run: cd ./packages/security/encrypted-secrets && pnpm test

      - name: Test security/encrypted-secrets-table
        run: cd ./packages/security/encrypted-secrets-table && pnpm test

      - name: Test security/ext-default-roles
        run: cd ./packages/security/ext-default-roles && pnpm test

      - name: Test security/ext-jwt-claims
        run: cd ./packages/security/ext-jwt-claims && pnpm test

      - name: Test security/ext-verify
        run: cd ./packages/security/ext-verify && pnpm test

      - name: Test utils/defaults
        run: cd ./packages/utils/defaults && pnpm test

      - name: Test utils/faker
        run: cd ./packages/utils/faker && pnpm test

      - name: Test utils/totp
        run: cd ./packages/utils/totp && pnpm test

      - name: Test utils/utils
        run: cd ./packages/utils/utils && pnpm test

